### ISSUE TITLE
CSV of scores and historical data for 2008, 2012, 2016?

### ISSUE THREAD

**Issue by briatte** [waxpancake/memeorandum-colors#2]
Dear Waxy,

Would it be possible to get the data behind Memeorandum Colors, possibly in CSV format, for both 2008 and 2012, and if possible after an update, for 2016 too?

Would be interesting to compare the composition and ideological scores of the 'online news ecology' through time, especially perhaps after the last election.

Thanks in advance –

~ the same perso who [just asked almost the same thing on Twitter](https://twitter.com/phnk/status/811646594042961924)

__Complement.__ Also, if Memorandum's owners agree, it would be great to get the raw data for the project (the Links x Links matrix), in order to run SVD (or any other equivalent algorithm) on different time periods.

**Comment by waxpancake** [comment]
@briatte You can get the 2012 data from Google Spreadsheets here: https://docs.google.com/spreadsheets/d/1x2G6jucO8mm2gSZ_7xBaf1WynyGBBIB5Yx90bbU2MAQ/edit#gid=0

2008 data is here:
https://docs.google.com/spreadsheets/d/1QXuIh7pBF5lsGxi-z80LFfVt9uF_XjI_FuWV2q-MaAU/edit?usp=sharing

I've asked Joshua about an update, but it seems unlikely. He lost all the source and doesn't have time to rebuild it.

**Comment by briatte** [comment]
Thanks!
